---
# yamllint disable rule:line-length
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main

jobs:
  Release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: variant-inc/actions-setup@renovate/actions-checkout-5.x
      - name: Create Release Action
        uses: variant-inc/actions-collection/create-release-tag@v2
